version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/crud-django1:/app
    ports: 
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=tasksdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=user
      - DATABASE_HOST=db
      - DATABASE_PORT=5432  
    restart: always   
    networks:
      - dawf2red

  db: 
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: tasksdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dawf2red 

networks:
  dawf2red:
    driver: bridge

volumes:
  postgres_data:
